version: '3'

services:
  app:
    image: finance_frontend:demo
    build: ./
    restart: always
    environment:
      PROJECT_ENV: production
      NODE_ENV: production
    ports:
      - '9002:80'
