version: '3'

services:
  app:
    image: finance_frontend:demo
    build: ./
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - /data/stone/finance_frontend/node_modules:/app/node_modules
    ports:
      - '9002:80'
